Add Polish Language Support
KingContaria/seedqueue pull request #36
Opened 2024-08-12 19:15 UTC by memerson12

Polish language using translations [provided by @MadoBrick in the discord ](https://discord.com/channels/1262887973154848828/1272273974889550024/1272435221513506899)

2024-08-14 18:56 UTC, tildejustin requested changes
language file filenames should be all lowercase as they match to resource locations in game

2024-08-14 22:33 UTC, memerson12 commented
> language file filenames should be all lowercase as they match to resource locations in game

Updated. Didn't realize that Minecraft didn't use the standard. I just pulled the locale code from here https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html

2024-08-27 10:33 UTC, KingContaria commented
Thanks for the PR! :)
You'll need one more person verifying your translations, please check the newly added translations workflow: https://github.com/KingContaria/seedqueue/issues/66

2024-09-10 00:37 UTC, MiniaczQ reviewed
More or less correct, it's missing some entries compared to https://github.com/KingContaria/seedqueue/blob/main/src/main/resources/assets/seedqueue/lang/en_us.json

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.menu.config.useWall.notAvailable": "§c§oNie Dostępne",
```suggestion
  "seedqueue.menu.config.useWall.notAvailable": "§c§oNiedostępne",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.menu.benchmark.title": "SeedQueue Benchmark",
```suggestion
  "seedqueue.menu.benchmark.title": "Test Sprawności SeedQueue",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.menu.config.useWall.notAvailable.tooltip": "Używanie Ekranu Ściany potrzebuje zainstalowania tych modów::",
```suggestion
  "seedqueue.menu.config.useWall.notAvailable.tooltip": "Używanie Ekranu Ściany potrzebuje zainstalowania tych modów:",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.menu.keys.secondary.tooltip": "Kiedy zostanie naciśnięty klawisz główny, gra sprawdzi, czy wszystkie klawisze pomocnicze są również naciśnięte, zanim aktywuje się skrót klawiaturowy.",
```suggestion
  "seedqueue.menu.keys.secondary.tooltip": "Kiedy klawisz główny zostanie naciśnięty, gra sprawdzi, czy wszystkie klawisze pomocnicze są również naciśnięte, zanim aktywuje się skrót klawiaturowy.",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.menu.keys.blocking.tooltip": "Kiedy zostanie naciśnięty klawisz główny, gra sprawdzi, czy żadne klawisze blokujące §lnie§r są naciśnięte, zanim aktywuje się skrót klawiaturowy.",
```suggestion
  "seedqueue.menu.keys.blocking.tooltip": "Kiedy klawisz główny zostanie naciśnięty, gra sprawdzi, czy żadne klawisze blokujące §lnie§r są naciśnięte, zanim aktywuje się skrót klawiaturowy.",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.key.cancelBenchmark": "Skończ Benchmark",
```suggestion
  "seedqueue.key.startBenchmark": "Zacznij Test Sprawności",
  "seedqueue.key.cancelBenchmark": "Zakończ Test Sprawności",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "speedrunapi.config.seedqueue.category.debug": "Ustawienia Debugujące",
```suggestion
  "speedrunapi.config.seedqueue.category.debug": "Ustawienia Odpluskwiania",
```
😄

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "speedrunapi.config.seedqueue.option.maxCapacity": "Maksymalna Ilość Seedów w Kolejce",
Minecraft tłumaczy na `ziarno`, ale jak nie tłumaczymy `SeedQueue` to można zostać przy tym

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.key.lock": "Użyj Kłódki na Świat",
```suggestion
  "seedqueue.key.lock": "Przypnij Świat",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "seedqueue.key.playNextLock": "Zagraj w Następną Kłódkę",
```suggestion
  "seedqueue.key.playNextLock": "Zagraj w Następny Przypięty Świat",
```

2024-09-10 00:37 UTC, MiniaczQ commented on src/main/resources/assets/seedqueue/lang/pl_pl.json
> +  "speedrunapi.config.seedqueue.option.freezeLockedPreviews.description": "Jeśli ta opcja jest włączona, zablokowane podglądy nie będą otrzymywać nowych chunków, a ich podgląd nie będzie aktualizowan
```suggestion
  "speedrunapi.config.seedqueue.option.freezeLockedPreviews": "Zamróź Przypięte Podglądy",
  "speedrunapi.config.seedqueue.option.freezeLockedPreviews.description": "Jeśli ta opcja jest włączona, przypięte podglądy nie będą otrzymywać nowych chunków i ich podgląd nie będzie aktualizowany",
```

2024-09-11 05:14 UTC, memerson12 commented
> More or less correct, it's missing some entries compared to https://github.com/KingContaria/seedqueue/blob/main/src/main/resources/assets/seedqueue/lang/en_us.json

That's because the PR was made very early on and some translation keys were added later. I went ahead and committed your suggested changes.

2024-10-06 20:30 UTC, KingContaria commented
I will take this as a verification and probably merge the translations with 1.4

2024-11-23 01:00 UTC, KingContaria approved these changes

2024-11-23 01:01 UTC, merged