Logging of information about the current system
KingContaria/seedqueue pull request #51
Opened 2024-08-14 03:48 UTC by Crystal15118

Information about the system is printed to the log file when client is initialized.

2024-08-14 17:09 UTC, tesselslate commented on src/main/java/me/contaria/seedqueue/SeedQueue.java
> +        LOGGER.info("Available Processors (Cores): {}", Runtime.getRuntime().availableProcessors());
IIRC it is indeed affected by affinity, at least on Linux. I had Minecraft crash logs saying I had only 2 processors despite having 24 due to affinity.

2024-08-14 18:42 UTC, KingContaria requested changes

2024-08-14 18:42 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/SeedQueue.java
> +        int totalProcessors = getTotalProcessors();
Could you just inline these and remove the `getTotalProcessors` method?

2024-08-14 18:42 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/SeedQueue.java
> +        LOGGER.info("Free Memory (MB): {}", Runtime.getRuntime().freeMemory() / (1024 * 1024));
Correct me if I'm wrong, but `Runtime#totalMemory` returns the amount of RAM used at that very moment, which isn't useful and `Runtime#freeMemory` also isn't helpful.
Max Memory seems to be Allocated Memory and if there is some kind of way to get the systems total memory through `ManagementFactory` that would be helpful information

2024-08-14 18:42 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/SeedQueue.java
> +        LOGGER.info("JVM Arguments: {}", String.join(" ", java.lang.management.ManagementFactory.getRuntimeMXBean().getInputArguments()));
No need to specify `java.lang.management.ManagementFactory`, just `ManagementFactory` works.

2024-08-15 07:31 UTC, Crystal15118 commented on src/main/java/me/contaria/seedqueue/SeedQueue.java
> +        LOGGER.info("Available Processors (Cores): {}", Runtime.getRuntime().availableProcessors());
> IIRC it is indeed affected by affinity, at least on Linux. I had Minecraft crash logs saying I had only 2 processors despite having 24 due to affinity.

fixed :)

2024-08-15 16:57 UTC, KingContaria reviewed
Lgtm, please make a test build and have atleast one person using mac, linux and windows test if it prints the correct values

2024-08-15 17:25 UTC, maskersss commented
> `Runtime#totalMemory` returns the amount of RAM used at that very moment, which isn't useful and `Runtime#freeMemory` also isn't helpful

is it not? would something like "current amount of free ram + current amount of ram used by minecraft" not be a good way to judge how much ram you can allocate? obviously there's going to be some rng in how much ram everything is using, but it still sounds useful to me
the only issue i can maybe see with it is if OS is paging some memory, idk if it's possible to figure it out, but there could be more issues i haven't thought of

2024-08-15 17:27 UTC, KingContaria commented
`Runtime#maxMemory` gives the amount of allocated ram

2024-08-15 17:32 UTC, maskersss commented
oh i think i misunderstood what this means, is `Runtime#totalMemory` / `Runtime#freeMemory` referring to the amount of total/free memory used by the java process? i thought it was about ram on your pc in general mb
in this case, still, would it be useful/possible/has it been implemented to check the amount of free ram on your pc (accounting for obs and stuff)?

2024-08-15 17:33 UTC, KingContaria commented
It could be helpful in some cases but misleading in others because from reading the log we can't know if they started OBS before or after Minecraft

2024-08-15 17:35 UTC, tildejustin commented
could you add a system property to disable this? I didn't like sleepbg config printing so I'd rather be able to turn this off as well and be able to read my logs easier.

2024-08-15 17:37 UTC, Crystal15118 commented
> could you add a system property to disable this? I didn't like sleepbg config printing so I'd like to be able to turn this off as well and be able to read my logs easier.

i can but it will likely take much more time and i don't think it would be as worth it as the effort but let's see what others say as well

2024-08-15 17:40 UTC, KingContaria commented
I'm not opposed to a system property

2024-08-16 13:52 UTC, KingContaria approved these changes
Lgtm, thank you :)

2024-08-16 13:55 UTC, merged