fix: better "percentage generated" calculation
KingContaria/seedqueue pull request #69
Opened 2024-08-31 20:05 UTC by tildejustin

counts out in rings, better guarding against beach spawns

2024-08-31 20:22 UTC, tildejustin commented on src/main/java/me/contaria/seedqueue/mixin/server/WorldGenerationProgressLoggerMixin.java
> +        return map.containsKey(new ChunkPos(x, z).toLong());
meant to make a method that generates this long without instantiating an object, is this a performance concern?

2024-09-01 10:26 UTC, KingContaria commented
Is there a specific reason the logic has to be in `WorldGenerationProgressLogger`? By putting it in `WorldGenerationProgressTracker` you could simply use the existing map of chunk statuses to check against

2024-09-01 16:20 UTC, tildejustin commented
i just put it in the logger b/c it seemed more natural to go there, but putting it in the tracker also works

2024-09-06 21:39 UTC, KingContaria requested changes
Could you cache the result of `seedQueue$getProgressPercentage` and just set it to `-1` when a new full chunk is added or the center changes to mark it as dirty?

A related issue is that right now progress percentage is affected by server-client delay because minecrafts `QueueingWorldGenerationProgressListener` schedules the updates to be run on the client. Since we suppress the logging anyway, it might be possible to just execute them directly if in queue. Concern would be if it changes accuracy of chunkmap freezing. This isn't blocking for this PR but since it's related I thought id bring it up.

2024-09-06 21:39 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/mixin/client/WorldGenerationProgressTrackerMixin.java
> +    private int totalCount;
No need to save this in a field

2024-09-06 21:39 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/mixin/client/WorldGenerationProgressTrackerMixin.java
> +        while (!end) {
Could you make this a for loop that terminates when it reaches the max radius or end is false?

2024-09-06 21:39 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/mixin/server/MinecraftServerMixin.java
> +            if (entry.getProgressPercentage() >= SeedQueue.config.maxWorldGenerationPercentage) {
You can merge these if-statements, they were only seperate because of the tracker variable

2024-09-23 11:32 UTC, merged