main group filling order
KingContaria/seedqueue pull request #77
Opened 2024-10-15 01:12 UTC by luvvlyjude

resource pack option to fill the main group in different orders, random, and backwards

i wanted to add this because then if i do 3x3 and 9 max queued then it looks like how classic wall would look with randomly previews appearing.

2024-10-15 02:00 UTC, KingContaria requested changes

2024-10-15 14:47 UTC, sathya-pramodh commented
Goat!!!!!

2024-10-25 20:41 UTC, KingContaria requested changes

2024-10-25 20:41 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/customization/Layout.java
> +                jsonObject.has("mainFillOrder") ? MainFillOrder.valueOf(jsonObject.get("mainFillOrder").getAsString().toUpperCase()) : MainFillOrder.FORWARD);
`String#toUpperCase` is sensitive to localization, please use `toUpperCase(Locale.ROOT)` instead

2024-10-25 20:41 UTC, KingContaria commented on src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java
> +        ArrayList<Integer> previewsOrder = IntStream.range(0, this.mainPreviews.length).collect(ArrayList::new, List::add, List::addAll);
Please use fastutils `IntArrayList` here

2024-10-26 12:08 UTC, KingContaria approved these changes
Lgtm, thank you! Will hold off on merging until i start work on the 1.4 update

2024-10-26 19:16 UTC, luvvlyjude commented
yay yay yippee iyipeeeeee I did it thanks I appreciate i thanks 😊 ☺

2024-11-23 00:49 UTC, merged